### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by rothwerx** [BriteSnow/gtx#1]
Hello, could you provide a license for this project?

**Comment by jeremychone** [comment]
Done, Apache-2 added to package.json, and new version 0.6.1 published. 

Btw, been a long time I have not updated this lib. We are still using it in some of our code, but I am sure there are many improvements needed (e.g., Path2D). Anyway, feel free to use as is, cherrypick what you need, or do pull request.

**Comment by rothwerx** [comment]
Thank you!
